name: Build
on: workflow_dispatch

jobs:
  BuildAll:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: BuildJammy
        run: |
           cp .env.example .env
           sed -i 's/REGISTRY=".*"/REGISTRY="local"/g' .env
           sed -i 's/BUILDER=".*"/BUILDER="local\/seafile\/builder:jammy"/g' .env
           sed -i 's/docker buildx create/docker buildx create --config .\/buildkit.toml/g' ./build_image.sh
           sed -i 's/docker run -it --rm/docker run --rm/g' ./build_with_docker.sh
           sed -i 's/--pull always.*/--pull missing \\/g' ./build_with_docker.sh
           chmod 755 ./build.sh
           chmod 755 ./build_with_docker.sh
           chmod 755 ./build_image.sh
           sudo apt-get install ca-certificates curl gnupg -y
           sudo install -m 0755 -d /etc/apt/keyrings
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
           sudo chmod a+r /etc/apt/keyrings/docker.gpg
           echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update
           sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
           ./build_image.sh -t jammy -t latest -l amd64
           ./build_with_docker.sh -T -A -P amd64
           ./build_image.sh -t jammy -t latest -l arm64
           ./build_with_docker.sh -T -A -P arm64
           ./build_image.sh -t jammy -t latest -l arm/v7
           ./build_with_docker.sh -T -A -P arm/v7
           ./build_image.sh -t jammy -t latest -l arm/v6
           ./build_with_docker.sh -T -A -P arm/v6
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            build/**/built-seafile-server-pkgs
